

spring:

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB

  profiles:
    include:
      - aws

logging:
  level:
    org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket: spring-kiri-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true


server:
  port: 8081
  servlet:
    context-path: /